services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '6443:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  service:
    env_file:
      - .env
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8085:8080'

volumes:
  pg_data: