// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	DeleteSubscription(ctx context.Context, code uuid.UUID) error
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	GetWaitingsNotification(ctx context.Context) ([]uuid.UUID, error)
	HaveActiveSubscription(ctx context.Context, email string) (bool, error)
	SetSendedNow(ctx context.Context, id uuid.UUID) error
	UpdateSubscriptionStatusByCode(ctx context.Context, status string, confirmationCode uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
